// NOTE: do not import directly from antd. Instead, add style here in alphabetical order, then import from styles/antd. This will hopefully prevent the conflicting order issue.

import $Badge from "antd/lib/badge";
import "antd/lib/badge/style";
import $Breadcrumb from "antd/lib/breadcrumb";
import "antd/lib/breadcrumb/style";
import $Button from "antd/lib/button";
import "antd/lib/button/style";
import $Card from "antd/lib/card";
import "antd/lib/card/style";
import $Checkbox from "antd/lib/checkbox";
import "antd/lib/checkbox/style";
import $Col from "antd/lib/col";
import "antd/lib/col/style";
import $DatePicker from "antd/lib/date-picker";
import "antd/lib/date-picker/style";
import $Descriptions from "antd/lib/descriptions";
import "antd/lib/descriptions/style";
import $Form from "antd/lib/form";
import "antd/lib/form/style";
import $Icon from "antd/lib/icon";
import "antd/lib/icon/style";
import $Input from "antd/lib/input";
import $InputNumber from "antd/lib/input-number";
import "antd/lib/input-number/style";
import "antd/lib/input/style";
import $Modal from "antd/lib/modal";
import "antd/lib/modal/style";
import $Radio from "antd/lib/radio";
import "antd/lib/radio/style";
import $Row from "antd/lib/row";
import "antd/lib/row/style";
import $Select from "antd/lib/select";
import "antd/lib/select/style";
import $Table from "antd/lib/table";
import "antd/lib/table/style";
import $Timeline from "antd/lib/timeline";
import "antd/lib/timeline/style";
import $Tooltip from "antd/lib/tooltip";
import "antd/lib/tooltip/style";
import $Upload from "antd/lib/upload";
import "antd/lib/upload/style";

export const Badge = $Badge;
export const Breadcrumb = $Breadcrumb;
export const Button = $Button;
export const Card = $Card;
export const Checkbox = $Checkbox;
export const Col = $Col;
export const DatePicker = $DatePicker;
export const Descriptions = $Descriptions;
export const Form = $Form;
export const Icon = $Icon;
export const Input = $Input;
export const InputNumber = $InputNumber;
export const Modal = $Modal;
export const Radio = $Radio;
export const Row = $Row;
export const Select = $Select;
export const Table = $Table;
export const Timeline = $Timeline;
export const Tooltip = $Tooltip;
export const Upload = $Upload;
